AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sneaker Store API using Aurora MySQL and AWS Secrets Manager

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 60
    MemorySize: 512
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:

  PostShoesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PostShoes
      StageName: dev
      DefinitionUri: openapi.yaml

  PostShoesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: seedShoes.handler
      CodeUri: src/handlers/
      Role: arn:aws:iam::441651574722:role/service-role/shoe_seeder-role-ltrdul30
      Events:
        PostShoesAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PostShoesApi
            Path: /shoes
            Method: POST
      Environment:
        Variables:
          SECRET_NAME: admin_cred
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-07bd9d46068308407
        SubnetIds:
          - subnet-0b1bbdc0446135392
          - subnet-046708b2fac504b7a

  GetShoesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getShoes.handler
      CodeUri: src/handlers/
      Role: arn:aws:iam::441651574722:role/service-role/shoe_seeder-role-ltrdul30
      Events:
        GetShoesAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PostShoesApi
            Path: /shoes
            Method: GET
      Environment:
        Variables:
          SECRET_NAME: admin_cred
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-07bd9d46068308407
        SubnetIds:
          - subnet-0b1bbdc0446135392
          - subnet-046708b2fac504b7a

  GetShoeByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getshoe.handler
      CodeUri: src/handlers/
      Role: arn:aws:iam::441651574722:role/service-role/shoe_seeder-role-ltrdul30
      Events:
        GetShoeByIdAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PostShoesApi
            Path: /shoes/{id}
            Method: GET
      Environment:
        Variables:
          SECRET_NAME: admin_cred
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-07bd9d46068308407
        SubnetIds:
          - subnet-0b1bbdc0446135392
          - subnet-046708b2fac504b7a

  PutShoeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: updateShoes.handler
      CodeUri: src/handlers/
      Role: arn:aws:iam::441651574722:role/service-role/shoe_seeder-role-ltrdul30
      Events:
        PutShoeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PostShoesApi
            Path: /shoes/{id}
            Method: PUT
      Environment:
        Variables:
          SECRET_NAME: admin_cred
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-07bd9d46068308407
        SubnetIds:
          - subnet-0b1bbdc0446135392
          - subnet-046708b2fac504b7a

  DeleteShoeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deleteShoes.handler
      CodeUri: src/handlers/
      Role: arn:aws:iam::441651574722:role/service-role/shoe_seeder-role-ltrdul30
      Events:
        DeleteShoeAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PostShoesApi
            Path: /shoes/{id}
            Method: DELETE
      Environment:
        Variables:
          SECRET_NAME: admin_cred
          REGION: us-east-1
      VpcConfig:
        SecurityGroupIds:
          - sg-07bd9d46068308407
        SubnetIds:
          - subnet-0b1bbdc0446135392
          - subnet-046708b2fac504b7a

  ListImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: imageList.handler
      CodeUri: src/handlers/
      Role: arn:aws:iam::441651574722:role/service-role/shoe_seeder-role-ltrdul30
      Events:
        ListImagesAPI:
          Type: Api
          Properties:
            RestApiId: !Ref PostShoesApi
            Path: /images
            Method: GET
      Environment:
        Variables:
          REGION: us-east-1
      # This one doesn't need DB access, so no VPC needed

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${PostShoesApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"

